### PR TITLE
Fix duplication of event during creation in iOS

### PR DESCRIPTION
**Pull request by jsilvestre**

### CODE REVIEW

**Comment by jsilvestre** [comment]
@frankrousseau there was a problem on some of the builds, I restarted them to see.

**Comment by frankrousseau** [comment]
Ok, I should have wait they finished.

**Comment by jsilvestre** [comment]
Well apparently you can't rerun tests when the PR is merged, Travis can't find the branch. But it looks good: https://travis-ci.org/cozy/cozy-sync/builds/135059496

**Comment by frankrousseau** [comment]
ok good.

**Comment by frankrousseau** [comment]
Btw, thx for the fix!

**Pull request merged**
