### PR TITLE
Add group support : one addressbook per contac's tags.

### PR DESCRIPTION
**Pull request by jacquarg**
- Add group support : one addressbook per contac's tags.
- Add thunderbird in CardDav configuration (to use with SOGo extension).
- Update tests against multiples addressbooks handling.

In-progress ! depends on PR cozy-vcard#8  and next version of cozy-vcard.

### CODE REVIEW

**Comment by frankrousseau** [comment]
@jacquarg @aenario What is the status of this PR?

**Comment by aenario** [comment]
it probably works, but broke tests because we logically change the content of the vcard (adding categories).
Logically, client should grab the new version and all will be well.
Yet, it needs to be tested functionally and if it works, tests should be adapted for it.

**Comment by frankrousseau** [comment]
@jsilvestre @poupotte @clochix is there one of you who can handle it?

**Comment by frankrousseau** [comment]
@jacquarg Except the fact tests are failing, do you consider it as good to merge?

**Comment by jacquarg** [comment]
@frankrousseau : it's been a while, but yes, just a build and it will be good to merge. I am disappointed by the problems with the tests as I remember that I spend some time to enrich them and make them pass.  But travis as secrects...

**Comment by frankrousseau** [comment]
Ok I will handle it (in fact I hope I will have enough time for it). I will include it in the work on import/export/sync of contacts.

**Pull request merged**
