### PR TITLE
sync: enhancement design

### PR DESCRIPTION
**Pull request by kelukelu**
design enhancement + tutorial links added

### CODE REVIEW

**Comment by frankrousseau** [comment]
Wow that's fast! @m4dz Could you review it?

**Comment by m4dz** [comment]
Yep, I'm on it :)

**Comment by m4dz** [comment]
Hey! Thanks for your first PR on Cozy :+1:!

I like your choices and it seems good to me. Unfortunately, it seems that we previously forgot to update the fonts for the sync app. Can you add them to the PR to finish properly the design, like in https://github.com/m4dz/cozy-emails/commit/c16612ede00033db331fcd168807b110034723f0 ?

The font-upgrade guide:
1. take the `client/app/assets/fonts` folder from the [cozy-proxy](https://github.com/cozy/cozy-proxy) project
2. replace the current `client/app/assets/fonts` folder with the aforementioned one (you can safely remove the existing one)
3. add a link to the dedicated new `fonts.css` file (see https://github.com/m4dz/cozy-emails/commit/c16612ede00033db331fcd168807b110034723f0#diff-007320d9a0e87dd10825a6dd9aebbc9aR9)
4. Replace the `font-family` rules in the styl file to be consistent with the documentation in `fonts.css` file

Thanks a lot!

**Comment by frankrousseau** [comment]
@m4dz can we merge this PR?

**Comment by m4dz** [comment]
Absolutely, it's ok for me. Let's merge it! Thanks @kelukelu!

**Comment by frankrousseau** [comment]
Congrats @kelukelu for your first code in production !

**Pull request merged**
